/**
 *  \file  libclipboard-config.h
 *  \brief Configuration specific options
 *
 *  \copyright Copyright (C) 2016 Jeremy Tan.
 *             This file is released under the MIT license.
 *             See LICENSE for details.
 *
 *  \details NOTE: This file is automatically generated.
 */

#ifndef _LIBCLIPBOARD_CONFIG_H
#define _LIBCLIPBOARD_CONFIG_H

/** Major version of libclipboard **/
#define LIBCLIPBOARD_VERSION_MAJOR @LIBCLIPBOARD_VERSION_MAJOR@

/** Minor version of libclipboard **/
#define LIBCLIPBOARD_VERSION_MINOR @LIBCLIPBOARD_VERSION_MINOR@

/* Depending on current system, define macros */
#if ( defined(_WIN32) || defined(WIN32) )
    #define LIBCLIPBOARD_BUILD_WIN32
#elif ( (defined(__APPLE__) && defined(__MACH__)) )
    #define LIBCLIPBOARD_BUILD_COCOA
#elif ( defined(__unix__) || defined(__unix) )
    #define LIBCLIPBOARD_BUILD_X11
#endif

#endif /* _LIBCLIPBOARD_CONFIG_H */
